void main()
{
	asm(" xchg %bx, %bx");
asm(" xchg %bx, %bx");
asm(" xchg %bx, %bx");
asm(" xchg %bx, %bx");
asm(" xchg %bx, %bx");
asm(" xchg %bx, %bx");
asm(" xchg %bx, %bx");
asm(" xchg %bx, %bx");
asm(" xchg %bx, %bx");
asm(" xchg %bx, %bx");
asm(" xchg %bx, %bx");
asm(" xchg %bx, %bx");
asm(" xchg %bx, %bx");
asm(" xchg %bx, %bx");
asm(" xchg %bx, %bx");
asm(" xchg %bx, %bx");
asm(" xchg %bx, %bx");
asm(" xchg %bx, %bx");
asm(" xchg %bx, %bx");
asm(" xchg %bx, %bx");
asm(" xchg %bx, %bx");
asm(" xchg %bx, %bx");
asm(" xchg %bx, %bx");
asm(" xchg %bx, %bx");
asm(" xchg %bx, %bx");
asm(" xchg %bx, %bx");
asm(" xchg %bx, %bx");
asm(" xchg %bx, %bx");
asm(" xchg %bx, %bx");
asm(" xchg %bx, %bx");
asm(" xchg %bx, %bx");
asm(" xchg %bx, %bx");
asm(" xchg %bx, %bx");
asm(" xchg %bx, %bx");
asm(" xchg %bx, %bx");
asm(" xchg %bx, %bx");
asm(" xchg %bx, %bx");
asm(" xchg %bx, %bx");
asm(" xchg %bx, %bx");
	while(1);
}
